# =============================================================================
# Main Infrastructure — Workspace & Lakehouses
# =============================================================================
#
# This module provisions the DEVELOPMENT workspace only.
# Test and Production workspaces are created by the CI/CD pipeline
# (Azure DevOps + fabric-cicd) when deploying to those environments.
#
# Architecture:
#   Development Workspace
#   ├── Lakehouse_Bronze   (raw data, enableschemas=true)
#   ├── Lakehouse_Silver   (curated data, enableschemas=true)
#   └── [Items imported by fabric-cli: Notebooks, Copy Jobs, etc.]
# =============================================================================

locals {
  workspace_name = "${var.workspace_prefix}_${var.username}"
}

# -----------------------------------------------------------------------------
# Capacity Lookup
# -----------------------------------------------------------------------------

data "fabric_capacity" "this" {
  display_name = var.capacity_name
}

# -----------------------------------------------------------------------------
# Development Workspace
# -----------------------------------------------------------------------------

resource "fabric_workspace" "dev" {
  display_name = local.workspace_name
  description  = var.workspace_description
  capacity_id  = data.fabric_capacity.this.id
}

# Grant SPN admin access (only if spn_object_id is provided)
resource "fabric_workspace_role_assignment" "spn_admin" {
  count = var.spn_object_id != null ? 1 : 0

  workspace_id = fabric_workspace.dev.id
  principal = {
    id   = var.spn_object_id
    type = "ServicePrincipal"
  }
  role = "Admin"
}

# Grant user admin access when using SPN auth (so user can manage the workspace)
resource "fabric_workspace_role_assignment" "user_admin" {
  count = var.upn_object_id != null ? 1 : 0

  workspace_id = fabric_workspace.dev.id
  principal = {
    id   = var.upn_object_id
    type = "User"
  }
  role = "Admin"
}

# -----------------------------------------------------------------------------
# Lakehouses (Medallion Architecture)
# -----------------------------------------------------------------------------

resource "fabric_lakehouse" "bronze" {
  display_name = var.bronze_lakehouse_name
  workspace_id = fabric_workspace.dev.id
  description  = "Bronze layer — raw ingested data (t2, t3_dev, t3_prod tables)"

  configuration = {
    enable_schemas = var.enable_lakehouse_schemas
  }
}

resource "fabric_lakehouse" "silver" {
  display_name = var.silver_lakehouse_name
  workspace_id = fabric_workspace.dev.id
  description  = "Silver layer — curated data (t1 table, t2/t3 shortcuts from Bronze)"

  configuration = {
    enable_schemas = var.enable_lakehouse_schemas
  }

  # Create Silver after Bronze to avoid overwhelming the Fabric API rate limiter.
  # The Fabric provider uses long-running operation (LRO) polling, and concurrent
  # lakehouse creates can trigger HTTP 429 "RequestBlocked" responses.
  depends_on = [fabric_lakehouse.bronze]
}

# -----------------------------------------------------------------------------
# Post-Apply: Generate configuration for fabric-cli scripts
# -----------------------------------------------------------------------------

resource "local_file" "terraform_outputs" {
  filename = "${path.module}/../.terraform-outputs.env"
  content  = <<-EOT
# Auto-generated by Terraform — do not edit manually
# Source: terraform/main.tf
# Generated: ${timestamp()}
WORKSPACE_NAME="${local.workspace_name}"
WORKSPACE_ID="${fabric_workspace.dev.id}"
CAPACITY_ID="${data.fabric_capacity.this.id}"
CAPACITY_NAME="${var.capacity_name}"
BRONZE_LAKEHOUSE_ID="${fabric_lakehouse.bronze.id}"
SILVER_LAKEHOUSE_ID="${fabric_lakehouse.silver.id}"
BRONZE_LAKEHOUSE_NAME="${var.bronze_lakehouse_name}"
SILVER_LAKEHOUSE_NAME="${var.silver_lakehouse_name}"
USERNAME="${var.username}"
EOT

  file_permission = "0600"
}
