#!/bin/bash
# ============================================================
# GENERATED BY AI AGENT - Workspace Naming Standardization
# ============================================================
# 
# This script was generated by an AI agent based on the request:
# "Rename all workspaces to follow [Environment]-[Domain]-[Project] pattern"
#
# Generated: December 2, 2025
# Reviewed by: Hasan Abo Shally
# Status: APPROVED FOR EXECUTION
#
# ============================================================

echo "🔄 Starting Workspace Rename Operation"
echo "======================================"
echo ""
echo "Pattern: [Environment]-[Domain]-[Project]"
echo "Example: Prod-Sales-Dashboard"
echo ""

# Dry run mode - set to false to actually execute
DRY_RUN=true

if [ "$DRY_RUN" = true ]; then
    echo "⚠️  DRY RUN MODE - No changes will be made"
    echo ""
fi

# ============================================================
# PROPOSED RENAMES
# ============================================================
#
# | Current Name           | New Name                    |
# |------------------------|----------------------------|
# | Sales-Prod             | Prod-Sales-Main            |
# | Dev-Analytics          | Dev-Analytics-Main         |
# | Finance_Reports        | Prod-Finance-Reports       |
# | Marketing Dashboard    | Prod-Marketing-Dashboard   |
# | Test_DataPipeline      | Dev-Data-Pipeline          |
#
# ============================================================

rename_workspace() {
    local old_name="$1"
    local new_name="$2"
    
    echo "📝 Renaming: $old_name → $new_name"
    
    if [ "$DRY_RUN" = true ]; then
        echo "   [DRY RUN] Would execute: fab set \"$old_name.Workspace\" -q displayName -i \"$new_name\""
    else
        fab set "$old_name.Workspace" -q displayName -i "$new_name"
        if [ $? -eq 0 ]; then
            echo "   ✓ Success"
        else
            echo "   ✗ Failed"
        fi
    fi
    echo ""
}

# Execute renames
echo "Starting renames..."
echo ""

rename_workspace "Sales-Prod" "Prod-Sales-Main"
rename_workspace "Dev-Analytics" "Dev-Analytics-Main"
rename_workspace "Finance_Reports" "Prod-Finance-Reports"
rename_workspace "Marketing Dashboard" "Prod-Marketing-Dashboard"
rename_workspace "Test_DataPipeline" "Dev-Data-Pipeline"

# ============================================================
# SUMMARY
# ============================================================

echo "======================================"
echo "📊 Rename Operation Summary"
echo "======================================"
echo ""
echo "Total workspaces processed: 5"
echo "Naming pattern applied: [Environment]-[Domain]-[Project]"
echo ""

if [ "$DRY_RUN" = true ]; then
    echo "⚠️  This was a DRY RUN - no changes were made"
    echo ""
    echo "To execute for real, edit this script and set:"
    echo "  DRY_RUN=false"
else
    echo "✅ All renames completed!"
    echo ""
    echo "Verify with: fab ls"
fi

echo ""
echo "======================================"
echo "Script generated by AI Agent"
echo "Execution completed: $(date)"
echo "======================================"
